### ISSUE TITLE
Error: [$injector:modulerr] Failed to instantiate module phonecatApp

### ISSUE THREAD

**Issue by mr-sachinkalekar** [angular/angular-phonecat#216]
I try running the index.html at step number 7. It is just showing blank html page. And when i go to the debugger it says the above error

Error: [$injector:modulerr] Failed to instantiate module phonecatApp due to:
[$injector:modulerr] Failed to instantiate module ngRoute due to:
[$injector:nomod] Module 'ngRoute' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by pjprogrammer1953** [comment]
I had the same problem as mr-sachinkalekar, struggled with it for days, and confounded my code school instructor and teacher assistant with it. Mr petebacondarwin's advice fixed the problem, which was so simple to resolve with proper module installation and configuration.

**Comment by fahadcv** [comment]
For me js file got downloaded from thirdparty component was empty :-)
Hope it may give some help to some one

**Comment by ChandruIonic** [comment]
Error: [$injector:modulerr] Failed to instantiate module starter due to:
[$injector:modulerr] Failed to instantiate module starter.routes due to:
[$injector:nomod] Module 'starter.routes' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.13/$injector/nomod?p0=starter.routes
minErr/<@file:///C:/Users/Techverve/Downloads/IonicServerSave-master/www/lib/ionic/js/ionic.bundle.js:8762:12
module/<@file:///C:/Users/Techverve/Downloads/IonicServerSave-master/www/lib/ionic/js/ionic.bundle.js:10466:1
ensure@file:///C:/Users/Techverve/Downloads/IonicServerSave-master/www/lib/ionic/js/ionic.bundle.js:10390:38
module@file:///C:/Users/Techverve/Downloads/IonicServerSave-master/www/lib/ionic/js/ionic.bundle.js:10464:1
loadModules/<@file:///C:/Users/Techverve/Downloads/IonicServerSave-master/www/lib/ionic/js/ionic.bundle.js:12796:22
forEach@file:///C:/User

**Comment by ChandruIonic** [comment]
Am getting above error while running can anyone help me?

**Comment by gkalpak** [comment]
Are you sure this is the right repo ?
You seem to be using ionic and execute `ionic.bundle.js` (which has nothing to do with `angular-phonecat`).

**Comment by ChandruIonic** [comment]
yep, its my angualar ionic framework application

**Comment by ChandruIonic** [comment]
Starter is my application name.. while route it gives like that

**Comment by gkalpak** [comment]
This repo is specifically for angular-phonecat.
You should ask for help over at ionic.

**Comment by meta-pratap-ranawat** [comment]
Error: [$injector:modulerr] Failed to instantiate module phonecatApp due to:
[$injector:modulerr] Failed to instantiate module phonecatControllers due to:
[$injector:nomod] Module 'phonecatControllers' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by sp1d3rino** [comment]
I spent a couple of hours to solve this problem, so when you see a message like this on :  

Error: [***] Failed to instantiate module phonecatApp due to: [***] Failed to instantiate module ngRoute due to: [*** Module 'ngRoute' is not available! You either misspelled the module name or forgot to load it.

check this points:
1) Include the module in app.js (where yuo define the angular.module) 
2) Include the js module file in the index.hml
3) include the module also in the controller

**Comment by ROJAHEMA** [comment]
I am getting this error.After adding acute.select dependencies.

Uncaught Error: [$injector:modulerr] Failed to instantiate module App due to:
Error: [$injector:modulerr] Failed to instantiate module newgen due to:
Error: [$injector:modulerr] Failed to instantiate module acute.select due to:
Error: [$injector:nomod] Module 'acute.select' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=acute.select
    at http://localhost:8080/project/js/angular-1.4.8.js:68:12
    at http://localhost:8080/project/js/angular-1.4.8.js:2005:17

Can you please guide me to overcome this issue
