### ISSUE TITLE
Problem to load list

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [angular/angular-phonecat#262]
@angular @IgorMinar @petebacondarwin @jeffbcross:

Hi guys, :smile: 

I tired to use your `angular-phonecat` code :pencil2: to list some wikis on the iSC Pedia website: https://iscpedia.github.io/de/ but **it didn't load the IDs**.

Where is the mistake and what should I do :question: 

*Repo: https://github.com/iSCPedia/iscpedia.github.io/tree/master/de*

Yours,
[**Suriyaa Kudo**]() :octocat:

**Comment by SuriyaaKudoIsc** [comment]
And?

**Comment by petebacondarwin** [comment]
@SuriyaaKudoIsc you should learn how to debug your code :-) This is a place to submit bugs in the phonecat project not for developer support. You should use the mailing list or StackOverflow instead for this.

But since I was looking anyway, the problem seems straightforward:

If you open up a console on that site, you will see that the server request for the wiki data failed with a 404 error.
This is because you put the wrong id in at https://github.com/iSCPedia/iscpedia.github.io/blob/master/de/js/services.js#L10

It should be `wiki` not `wikis`

**Comment by SuriyaaKudoIsc** [comment]
@petebacondarwin: Thanks for your help! :+1:
