### ISSUE TITLE
Close the random unnessary issues.

### ISSUE THREAD

**Issue by SilentFlame** [angular/angular-phonecat#310]
@petebacondarwin @IgorMinar 

can we please close some of the random unnecessary issues here like, #308, #291

they neither contain any description nor any sensible issue heading.
What you guys say?

**Comment by gkalpak** [comment]
Closed. Thx for pointing them out !

We are in the middle of a phonecat update, bringing it up to speed with the recently released Angular v1.5.0 (that will probably land next week). 
I plan to also do some issue clean-up as part of that.

**Comment by SilentFlame** [comment]
@gkalpak would love to help you in that regard.
let me know if I can contribute to your project somehow, either bug fixing, or clean-ups.

**Comment by gkalpak** [comment]
@SilentFlame, since you volunteered :stuck_out_tongue: :+1:
I have opened #326 which updated the tutorial to bring it up to speed with "modern" best practices and features (and will close a bunch of issues as well).

If you want to get a preview of the new version, any feedback it highly appreciated :smile: 
After that has been merged, we should go over the open issues/PRs again and see if the problems still exist.
