### ISSUE TITLE
git checkout -f step-0 returns error

### ISSUE THREAD

**Issue by DAT14WRomulusDanielNegut** [angular/angular-phonecat#336]
I tried also _git checkout -f step-1_ and it works! but _git checkout -f step-0_ returns error: pathspec 'step-0' did not match any file(s) known to git.

**Comment by gkalpak** [comment]
There was an update in progress a few minutes ago, maybe it was a temporary issue.
It works for me fine now. Could you try again now and let me know how it goes ? :smiley:

**Comment by gkalpak** [comment]
Thiking about it again, it might be because your clone is not "deep" enough. Previosuly, the instructions used `--depth=14`, but now we 2 extra steps, so the instructions are updated to use `--depth=16`.

Try deleting the local directory and clone the remote repo again:

```
rm -rf angular-phonecat
git clone --depth=16 https://github.com/angular/angular-phonecat.git
```

(Also, make sure to reload the tutorial page on https://docs.angularjs.org/tutorial to get the new content.)

**Comment by DAT14WRomulusDanielNegut** [comment]
Yes it is fine now. Thank you!
