### ISSUE TITLE
Tutorial on page and diff version

### ISSUE THREAD

**Issue by PeterLabos** [angular/angular-phonecat#338]
Hi, this is not exactly an issue as little inconvenience.
Will be tutorial on page https://docs.angularjs.org/tutorial/step_11 Custom filters matching diff on github?
Oh great, now step 11 is mixed with step 13 on description page. When the changes to tutorial will be finished? So I can continue with it, or start from scratch. I was just in the middle of tutorial.
Git changes are already done completely? Or there will be more in next days?

**Comment by gkalpak** [comment]
The tutorial changes are done (they were all done yesterday). In case you haven't already, make sure to refresh the page (https://docs.angularjs.org/tutorial) to get the new content. You also need to clone the repo again (with `--depth=16` this time, because there are a couple new steps).

--
BTW, the old tutorial is still available on the 1.4.x docs and the corresponding code is on the `pre-1.5.0-snapshot` branch of the `angular-phonecat` repo, but the links to code diffs and live demos aren't working properly (they are pointing to the new code/demos). 

I will fix it soon (hopefully today), in case you want to continue with tge old one, but I really recommend checking out the latest version.

--
I understand this is pretty inconvenient for people being halfway through the tutorial, but I hope the new content is worth it :smiley:

**Comment by PeterLabos** [comment]
I realised this morning that it can be a browser cache. Now it is working fine. I will start again with new version. Thanks for update.
