### ISSUE TITLE
what the differ of those version

### ISSUE THREAD

**Issue by KrisCheng** [angular/angular-phonecat#339]
hi! I come from China and I am translating this tutorial to Chinese those days. I just finished the step 5 yesterday. but the tutorial have changed to a new version today. is there any big difference between this two version. should I continue finish the whole translation of the older version or get start in the new?thank you

**Comment by gkalpak** [comment]
There are a few differences (mostly in terms of code organization into files and directories and switching to a component based architecture). Many steps are pretty similar to the old version (although their index might differ, because there were 2 new steps added).

It shouldn't be too much work adapting your translation so far to the new content, so I would go with the new one.
