### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by scj39** [angular/angular-phonecat#345]
Hoping to save someone else some time here. If you get the error mentioned in the title from the first line of one of your whatever.template.html files when proceeding from step 3 to 4, you may have misspelled the templateUrl() method as templateURL() in one of your component files. 

Curiously enough, if you add type="text/html" with the script tag that refers to the template file in question, it doesn't throw an error even if you use templateURL(). Additionally, if you inspect the resulting page's elements, you'll see that the custom component tag is being generated as of the "ng-isolate-scope" class. 

Anyone know why this is? Shouldn't it throw an error saying that there isn't a templateURL() method?

**Comment by gkalpak** [comment]
You can always checkout the final code for each step using git, so you avoid errors like these (although sometimes running into an error helps gain a deeper understanding of the underlying mechanics and avoid similar errors in the future). :+1: for coding along!

--
> if you add type="text/html" with the script tag that refers to the template file in question

Not sure what you mean. Could you post a code sample of what you described? 

> you'll see that the custom component tag is being generated as of the "ng-isolate-scope" class

This is added by Angular for debugging purposes (but can be disabled in production deployments). For more info see the [dev guide][1].

--
I'm going to close this, since it is not actionable, but feel free to continue the discussion below (e.g. if you have more questions).

[1]: https://docs.angularjs.org/guide/production#disabling-debug-data
