### ISSUE TITLE
Cannot find a version fro 1.3.0 

### ISSUE THREAD

**Issue by jpraval** [angular/angular-phonecat#354]
Do we have a phone-cat for 1.3.0 ?

**Comment by gkalpak** [comment]
Probably not. You can read the tutorial on the 1.3.x version of the docs ([here][1]), but there is no code available for that.

The closest we have is a tutorial version that is compatible with 1.4.x ([here][2]) and there is a good chance it is compatible with 1.3.x as well (but no guarantees). The code for the 1.4.x version of the tutorial can be found on the `1.4-snapshot` branch of this repo.

That said, 1.3.x is pretty old (and not maintained any more). Why do you want a tutorial for that?
Btw, the current version is 1.5.8 and that is the recommended version to use (and learn) :smiley:

--
I am going to close this, since it is not actionable, but feel free to continue the discussion below.

[1]: https://code.angularjs.org/1.3.20/docs/tutorial
[2]: https://code.angularjs.org/1.4.12/docs/tutorial
