### ISSUE TITLE
Explain more detail for Tutorial 13 - "REST and Custome Services"

### ISSUE THREAD

**Issue by ntlzz93** [angular/angular-phonecat#357]
Assume that we have a rest api to create,update,delete... phone cat. Please add some basic feature for rest and custome services such as create new phone, upade exits phone, also delete their . Enjoy it!

**Comment by gkalpak** [comment]
In order to support these operations, one needs a working backend (with logic, some form of persistent storage etc). Right now, we fake a server for `GET` requests, by serving JSON files directly. This helps keep the overhead low and keep the tutorial focused on Angular.

Adding all the necessary parts for what you suggest, would introduce new (non-Angular related) concepts and complicate things considerably (especially for beginners).

So, it is outside the scope of the tutorial imo.
If you can come up with a simple way of adding such functionality though, it might be a good addition for the [Developer Guide][1], which is targeted to more advanced users.

[1]: https://docs.angularjs.org/guide/services
