### ISSUE TITLE
npm Error

### ISSUE THREAD

**Issue by frans4** [angular/angular-phonecat#371]
While running npm run protractor in the terminal  protractor e2e-tests/protractor.conf.js failed. I will try and update node.js but the terminal to told me to notify the author but i believe that is the problem.

**Comment by gkalpak** [comment]
Thx for reporting. There is not enough info to diagnose further, though.

Make sure you are using the latest version of the tutorial and have all prerequisites and dependencies installed and up-to-date. If you still can't get it to work, post more details about the error you get and the OS/versions you are using.
(If anything, this sounds more like a protractor issue - not directly related to the tutorial.)

<sub>Closing, since this is not actionable in its current state.</sub>
