### ISSUE TITLE
protractor is not recognized as an internal or external command is appearing while executing test

### ISSUE THREAD

**Issue by nitikas** [angular/angular-phonecat#372]

**Comment by gkalpak** [comment]
If you have the dependencies installed (i.e. having run `npm install`) and run the test commands as described in the tutorial (i.e. `npm run protractor`), there should be no issue.

There is not enough info to diagnose further, but based on the issue description, I'd say you are trying to run protractor directly (i.e. `protractor`) instead of through npm. The correct command would be: `npm run protractor`).

Closing (since there doesn't seem to be anything wrong with `phonecat`), but feel free to continue the discussion below.

--
BTW, for support questions, such as this one, you can use one of the [general support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
