### ISSUE TITLE
Issue with npm install

### ISSUE THREAD

**Issue by zalenix** [angular/angular-phonecat#375]
Receiving error on following instruction on [(https://docs.angularjs.org/tutorial)] after executing:

`npm install`

![err](https://cloud.githubusercontent.com/assets/98243/19389469/2f8b4c82-91f2-11e6-97c6-f6112dd489ec.png)
(prompt hidden for privacy)

npm-debug.log : [http://pastebin.com/1CeH8bem]

**Comment by gkalpak** [comment]
It seems that either `bower` has not been installed properly or that there is a permissions issue. It could be because you have cloned the repository inside `Program Files`. You need administrative priviledges in order to modify `Program Files`, so it is not recommended to clone your repositories in there.

Try moving the repo in another location that does not require admin rights (e.g. create a new subdirectory inside your home folder) and then delete the `node_modules/` directory and re-run `npm install`.

**Comment by txwizard** [comment]
Attached log files demonstrate completely the same issue, and I have confirmed that the only components that are installed into the Program Files directory is Node.js, itself. A search of the Windows PATH directories and the CWD finds the following for bower.

C:\Users\DAVE\Documents\Programming\JQuery\Angular\PhoneCat\angular-phonecat\bower.json
C:\Users\DAVE\AppData\Roaming\npm\bower
C:\Users\DAVE\AppData\Roaming\npm\bower.cmd

[npm_SESSION_20161022_104715.TXT](https://github.com/angular/angular-phonecat/files/545871/npm_SESSION_20161022_104715.TXT)
[npm-debug_20161022_104715.TXT](https://github.com/angular/angular-phonecat/files/545870/npm-debug_20161022_104715.TXT)

I would very much like to do this tutorial, but this is my second go at it, with dismal results on both. On the first go, I tried to use my existing IIS Express installation to run it.

**Comment by gkalpak** [comment]
@txwizard, based on the logs, I would say you don't have git on your path. Can you verify that?

**Comment by txwizard** [comment]
Good call; although git is installed, I didn't put it on the path.

**Comment by gkalpak** [comment]
Great! Since we haven't heard back from the OP, I am going to close this. Happy to reooen if we get more feedback.
