### ISSUE TITLE
a clone question about this

### ISSUE THREAD

**Issue by CodeMagic6** [angular/angular-phonecat#390]
when I git clone this repositories. It always mentioned that ' RPC failed; curl 56 SSL read: error:00000000:lib(0):func(0):reason(0),errno 10054,fatal: The remote end hung up unexpectedly fatal: early EOF  fatal: index-pack failed'.Why

**Comment by gkalpak** [comment]
There can be different reasons (e.g. a low git buffer size or an outdated git version). What OS/version/git version are you using? What is the exact command that fails?

**Comment by CodeMagic6** [comment]
`PS C:\Users\Administrator\Desktop\NG-phonecat> git clone https://github.com/angular/angular-phonecat.git
Cloning into 'angular-phonecat'...
remote: Counting objects: 8038, done.
remote: Compressing objects: 100% (51/51), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: fatal: The remote end hung up unexpectedly
early EOF
fatal: index-pack failed
PS C:\Users\Administrator\Desktop\NG-phonecat>
PS C:\Users\Administrator\Desktop\NG-phonecat> git --version
git version 2.10.2.windows.1
PS C:\Users\Administrator\Desktop\NG-phonecat>`

Now,the error is different.above is the powershell message.My Git is 'git version 2.10.2.windows.1'.I git clone other repositories with nothing wrong,but I still can't solve this.Maybe because it is not in Linux?I use the command in git bash with 'git config --global http.postBuffer 524288000',but it can't help.

**Comment by gkalpak** [comment]
Windows is definitely not the problem (I am using Windows myself).

I have `git version 2.10.0.windows.1` and it works fine (always have been). I will try with the latest git to see if it is a git issue.

**Comment by gkalpak** [comment]
Everything (still) works for me with `git version 2.11.0.windows.1`. By looking around there seems to be several ossible causes for the errors (e.g. insufficient memory or requests timing out due to a slow network).

Can you try updating git to the latest version (just in case) and running the following command (to see if it helps):

```
git clone --depth=1 https://github.com/angular/angular-phonecat.git
```

That said, `angular-phonecat` is not a big repo and I would be a little surprized if it hit memory or timeout limits while other repos don't. Can you also try downloading a significantly larger repo (e.g. `https://github.com/angular/angular.git`) and see how it goes?

**Comment by CodeMagic6** [comment]
`PS C:\Users\Administrator\Desktop\wk> git --version`
`**git version 2.11.0.windows.1**`
`PS C:\Users\Administrator\Desktop\wk> git clone --depth=1 https://github.com/ang`
`ular/angular-phonecat.git`
`Cloning into 'angular-phonecat'...`
`remote: Counting objects: 157, done.`
`remote: Compressing objects: 100% (146/146), done.`
`remote: Total 157 (delta 14), reused 140 (delta 10), pack-reused 0Receiving obje`
`cts:  92% (145/157), 1.42 MiB | 26.00 KiB/s`
`Receiving objects: 100% (157/157), 1.43 MiB | 27.00 KiB/s, done.`
`Resolving deltas: 100% (14/14), done.`
`PS C:\Users\Administrator\Desktop\wk>`

**Well done.Your answer have resolve my problem.
But I have a question that the command(complete clone) 'git clone https://github.com/angular/angular
-phonecat.git' compared with the command(shadow clone) 'git clone --depth=1 https://github.com/angular/angular
-phonecat.git' have some different about the function?
That is the shadow clone can still promise all the function what the program offered?
If it can maybe I can use '--depth=1' in others repo the same way.It can save a lot of download time because of the network.**

**Below:clone angular**

`PS C:\Users\Administrator\Desktop> git clone https://github.com/angular/angular.`
`git`
`Cloning into 'angular'...`
`remote: Counting objects: 106703, done.`
`remote: Compressing objects: 100% (29/29), done.`
`error: RPC failed; curl 56 SSL read: error:00000000:lib(0):func(0):reason(0), er`
`rno 10054`
`fatal: The remote end hung up unexpectedly`
`fatal: early EOF`
`fatal: index-pack failed`

**I've tried angular.It has the same error.Then I've tried the shadow clone.works well.  Below**

`PS C:\Users\Administrator\Desktop> git clone --depth=1 https://github.com/angula`
`r/angular.git`
`Cloning into 'angular'...`
`remote: Counting objects: 1885, done.`
`remote: Compressing objects: 100% (1640/1640), done.`
`remote: Total 1885 (delta 281), reused 821 (delta 130), pack-reused 0`
`Receiving objects: 100% (1885/1885), 1.78 MiB | 36.00 KiB/s, done.`
`Resolving deltas: 100% (281/281), done.`

**Comment by gkalpak** [comment]
The `--depth=X` option tells git to only download the `X` last commits (by default it downloads the whole history of commits). Whether it is appropriate to use `--depth` depends on the usecase.

For example, if you are cloning a seed project to use as a starting point for a new project of yours, then you only care about the last commit, so `--depth=1` is suitable (and recommended). If you want to have the whole history of a project available (so you can search through older commits for example), then you should not use `--depth`.

For `angular-phonecat` specifically, you care about the last 16 commits iirc (because each one of the last 15 commits is a different step in the tutorial), so if you are using it the tutorial, it is recommended to use `--depth=16`.

##
Now, from the failures you described above, it sounds possible that your machine is out of space. Make sure you have enough space before cloning a repo.

I am going to close this issue, since it is not directly related to `angular-phonecat`, but feel free to continue the discussion below if you need more help.
