### ISSUE TITLE
step9: set hashPrefix('!') to locactorProvider break phoneDetail component

### ISSUE THREAD

**Issue by ilyuha21st** [angular/angular-phonecat#409]
Hello, I use angular and angular-route v.1.6.4. And trying to follow the tutorial, I found that setting $locationProvider.hashPrefix('!') in app.config.js is broke the 'phoneDetail' component triggering. Whenever I'm trying to click on any link on 'phoneList' template rendering, a url in browser sets to something like 'http://127.0.0.1:8000/#!/phones/#%2Fphones%2Fmotorola-xoom-with-wi-fi', and as result is not triggering 'phoneDetail' view. The work around is to set $locationProvider.hashPrefix('') (without '!') which is causing the correct url path: 'http://127.0.0.1:8000/#/phones/motorola-xoom-with-wi-fi'.
On a backend side I use django framework, but guess it's a generic issue, because depends of frontend part. Maybe I wrong... Please, change the tutorial or guide me right way.

**Comment by gkalpak** [comment]
The tutorial uses AngularJS v1.5.x (which has `''` as the default hashPrefix). In v1.6.x, the default hashPrefix is `'!'`. This means that:

- Links steps 1-8, will not work by default in v1.6.x. (In order to fix them, you need to configure `$locationProvider` to use `''` as the hashPrefix).
- Links in steps 9+ will work correctly in v1.6.x (although calling `$locationProvider.hashPrefix('!')` is redundant, since that is the default in v1.6.x).
