### ISSUE TITLE
Angular Protractor: How to ensure that “no specs found” error does not happen?

### ISSUE THREAD

**Issue by rupali317** [angular/angular-phonecat#425]
I have posted my issue at:

https://stackoverflow.com/questions/46500133/angular-protractor-how-to-ensure-that-no-specs-found-error-does-not-happen

Basically whenever I switch to different branches say step-2, step-3, step-4, the protractor will always show "no specs found" error. But the test works fine in master branch. Can you please let me know why this error message shows up? How to fix it?

**Comment by gkalpak** [comment]
I left [an answer][1] on the StackOverflow question. As a general guideline, in order to avoid confusion (and frustration) try to follow the instructions closely, until you get hang of AngularJS and the techniques and tools introduced in the tutorial.

[1]: https://stackoverflow.com/questions/46500133/angular-protractor-how-to-ensure-that-no-specs-found-error-does-not-happen/46515759#46515759
